import './globals.css';
import { Roboto } from 'next/font/google';
import Header from '@/components/Layout/Header';
import Footer from '@/components/Layout/Footer';
import Providers from './providers/Providers';
const roboto = Roboto({ subsets: ['latin'], weight: ['400', '700'] });

export const metadata = {
  title: 'A Blog Website',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="flex justify-center items-center">
      <body
        className={`${roboto.className} flex flex-col justify-between h-screen w-full`}
      >
        <Providers>
          <Header />
          <main className="h-full max-w-[1800px] p-2">{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
